USE [SISCOVI]
GO

/****** Object:  StoredProcedure [dbo].[P_SISCOVI_DATA_UNLOAD]    Script Date: 14/06/2018 16:32:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE procedure [dbo].[P_SISCOVI_DATA_UNLOAD]
AS

BEGIN

  DROP TABLE  TB_RETROATIVIDADE_PERCENTUAL;
  DROP TABLE  TB_RETROATIVIDADE_REMUNERACAO;
  DROP TABLE  TB_RETROATIVIDADE_TOTAL_MENSAL;
  DROP TABLE  TB_RETRO_PERCENTUAL_ESTATICO;
  DROP TABLE  TB_SALDO_RESIDUAL_DEC_TER;
  DROP TABLE  TB_SALDO_RESIDUAL_FERIAS;
  DROP TABLE  TB_SALDO_RESIDUAL_RESCISAO;
  DROP TABLE  TB_RESTITUICAO_DECIMO_TERCEIRO;
  DROP TABLE  TB_RESTITUICAO_FERIAS;
  DROP TABLE  TB_RESTITUICAO_RESCISAO;
  DROP TABLE  TB_TOTAL_MENSAL_A_RETER;
  DROP TABLE  TB_FUNCAO_TERCEIRIZADO;
  DROP TABLE  TB_TERCEIRIZADO_CONTRATO;
  DROP TABLE  TB_REMUNERACAO_FUN_CON;
  DROP TABLE  TB_FUNCAO_CONTRATO;
  DROP TABLE  TB_FUNCAO;
  DROP TABLE  TB_CONVENCAO_COLETIVA;
  DROP TABLE  TB_EVENTO_CONTRATUAL;
  DROP TABLE  TB_HISTORICO_GESTAO_CONTRATO;
  DROP TABLE  TB_PERCENTUAL_CONTRATO;
  DROP TABLE  TB_PERCENTUAL_ESTATICO;
  DROP TABLE  tb_percentual_dinamico;
  DROP TABLE  TB_PERFIL_GESTAO;
  DROP TABLE  TB_RUBRICA;
  DROP TABLE  TB_TERCEIRIZADO;
  DROP TABLE  TB_TIPO_EVENTO_CONTRATUAL;
  DROP TABLE  TB_TIPO_RESCISAO;
  DROP TABLE  TB_TIPO_RESTITUICAO;
  DROP TABLE  TB_CONTRATO;
  DROP TABLE  TB_USUARIO;
  DROP TABLE  TB_PERFIL_USUARIO;

  PRINT 'Script executado com sucesso'

END;
GO


