USE [SISCOVI]
GO

/****** Object:  StoredProcedure [dbo].[P_SISCOVI_DATA_UNLOAD]    Script Date: 14/06/2018 16:32:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE procedure [dbo].[P_SISCOVI_DATA_UNLOAD]
AS

BEGIN

  DELETE FROM TB_RETROATIVIDADE_PERCENTUAL;
  DELETE FROM TB_RETROATIVIDADE_REMUNERACAO;
  DELETE FROM TB_RETROATIVIDADE_TOTAL_MENSAL;
  DELETE FROM TB_RETRO_PERCENTUAL_ESTATICO;
  DELETE FROM TB_SALDO_RESIDUAL_DEC_TER;
  DELETE FROM TB_SALDO_RESIDUAL_FERIAS;
  DELETE FROM TB_SALDO_RESIDUAL_RESCISAO;
  DELETE FROM TB_RESTITUICAO_DECIMO_TERCEIRO;
  DELETE FROM TB_RESTITUICAO_FERIAS;
  DELETE FROM TB_RESTITUICAO_RESCISAO;
  DELETE FROM TB_TOTAL_MENSAL_A_RETER;
  DELETE FROM TB_FUNCAO_TERCEIRIZADO;
  DELETE FROM TB_TERCEIRIZADO_CONTRATO;
  DELETE FROM TB_REMUNERACAO_FUN_CON;
  DELETE FROM TB_FUNCAO_CONTRATO;
  DELETE FROM TB_FUNCAO;
  DELETE FROM TB_CONVENCAO_COLETIVA;
  DELETE FROM TB_EVENTO_CONTRATUAL;
  DELETE FROM TB_HISTORICO_GESTAO_CONTRATO;
  DELETE FROM TB_PERCENTUAL_CONTRATO;
  DELETE FROM TB_PERCENTUAL_ESTATICO;
  DELETE FROM tb_percentual_dinamico;
  DELETE FROM TB_PERFIL_GESTAO;
  DELETE FROM TB_RUBRICA;
  DELETE FROM TB_TERCEIRIZADO;
  DELETE FROM TB_TIPO_EVENTO_CONTRATUAL;
  DELETE FROM TB_TIPO_RESCISAO;
  DELETE FROM TB_TIPO_RESTITUICAO;
  DELETE FROM TB_CONTRATO;
  DELETE FROM TB_USUARIO;
  DELETE FROM TB_PERFIL_USUARIO;

  PRINT 'Script executado com sucesso'

END;
GO


